pipeline{
  agent any
  tools{
      maven 'Maven'
  }
  stages{
        stage("SCM Checkout"){
            steps{
              git 'https://github.com/nits1431/testmaven.git'
            }
        }
        stage("Maven Build"){
            steps{
                bat 'mvn clean package'
            }
        }
    }
}
